//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class conDB : DbContext
    {
        public conDB()
            : base("name=conDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tb_cliente> tb_cliente { get; set; }
        public virtual DbSet<tb_consulta> tb_consulta { get; set; }
        public virtual DbSet<tb_mascota> tb_mascota { get; set; }
        public virtual DbSet<tb_reserva> tb_reserva { get; set; }
        public virtual DbSet<tb_tipoMascota> tb_tipoMascota { get; set; }
        public virtual DbSet<tb_usuarioVet> tb_usuarioVet { get; set; }
    }
}
