//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_consulta
    {
        [Display(Name = "Identificador")]
        public string id_cons { get; set; }
        [Display(Name = "Fecha")]
        public System.DateTime fec_cons { get; set; }
        [Display(Name = "Sintoma")]
        public string sint_cons { get; set; }
        [Display(Name = "Diagmóstico")]
        public string diag_cons { get; set; }
        public string id_mas { get; set; }
    
        public virtual tb_mascota tb_mascota { get; set; }
    }
}
