//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_cliente()
        {
            this.tb_mascota = new HashSet<tb_mascota>();
            this.tb_reserva = new HashSet<tb_reserva>();
        }
        [Display(Name ="Identificador")]
        public string id_cli { get; set; }
        [Display(Name = "Nombre")]
        public string nom_cli { get; set; }
        [Display(Name = "Apellidos")]
        public string ape_cli { get; set; }
        [Display(Name = "Teléfono Fijo")]
        public string telFijo_cli { get; set; }
        [Display(Name = "Celular")]
        public string telMovil_cli { get; set; }
        [Display(Name = "Correo Electrónico")]
        public string cor_cli { get; set; }
        [Display(Name = "Dirección")]
        public string dir_cli { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_mascota> tb_mascota { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_reserva> tb_reserva { get; set; }
    }
}
