//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_mascota
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_mascota()
        {
            this.tb_consulta = new HashSet<tb_consulta>();
            this.tb_reserva = new HashSet<tb_reserva>();
        }
        [Display(Name ="Identificador")]
        public string id_mas { get; set; }
        [Display(Name = "Nombre")]
        public string nom_mas { get; set; }
        [Display(Name = "Fecha Nacimiento")]
        public System.DateTime fecNacimiento_mas { get; set; }
        [Display(Name = "Raza")]
        public string raza_mas { get; set; }
        [Display(Name = "Id Cliente")]
        public string id_cli { get; set; }
        [Display(Name = "Id Tipo Mascota")]
        public string id_tipMas { get; set; }
    
        public virtual tb_cliente tb_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_consulta> tb_consulta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_reserva> tb_reserva { get; set; }
        public virtual tb_tipoMascota tb_tipoMascota { get; set; }
    }
}
