//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_reserva
    {
        [Display(Name = "Identificador")]
        public string id_res { get; set; }
        [Display(Name = "Fecha")]
        public System.DateTime fec_res { get; set; }
        [Display(Name = "Id Cliente")]
        public string id_cli { get; set; }
        [Display(Name = "Id Mascota")]
        public string id_mas { get; set; }
        [Display(Name = "Id Usuario")]
        public Nullable<int> id_usu { get; set; }
    
        public virtual tb_cliente tb_cliente { get; set; }
        public virtual tb_mascota tb_mascota { get; set; }
        public virtual tb_usuarioVet tb_usuarioVet { get; set; }
    }
}
